Work in progress

diff --git a/build b/build
--- a/build
+++ b/build
@@ -4,10 +4,99 @@ set -e
 SELFDIR=`dirname "$0"`
 SELFDIR=`cd "$SELFDIR" && pwd`
 
-# TODO
-DATA_DIR="$SELFDIR/data"
-OUTPUT_DIR="$SELFDIR/output"
-mkdir -p "$DATA_DIR" "$OUTPUT_DIR"
+DATA_DIR=
+OUTPUT_DIR=
+X86_BINARIES=true
+X64_BINARIES=true
+CONCURRENCY=2
+SETUP_SOURCE=true
+COMPILE=true
+SANITY_CHECK_OUTPUT=true
+
+function usage()
+{
+	echo "Usage: ./build [options] <DATA DIR> <OUTPUT_DIR>"
+	echo "Build Traveling Ruby binaries."
+	echo
+	echo "Options:"
+	echo "  -t         Only build 32-bit binaries"
+	echo "  -T         Do not build 32-bit binaries"
+	echo "  -s         Only build 64-bit binaries"
+	echo "  -S         Do not build 64-bit binaries"
+	echo
+	echo "  -E         Do not setup source"
+	echo "  -C         Do not compile"
+	echo
+	echo "  -j NUMBER  Set build concurrency. Default: 2"
+	echo "  -h         Show this help"
+}
+
+function parse_options()
+{
+	local OPTIND=1
+	local opt
+	while getopts "tTsSECj:h" opt; do
+		case "$opt" in
+		t)
+			X84_BINARIES=true
+			X64_BINARIES=false
+			;;
+		T)
+			X84_BINARIES=false
+			;;
+		s)
+			X84_BINARIES=false
+			X64_BINARIES=true
+			;;
+		S)
+			X64_BINARIES=false
+			;;
+		E)
+			SETUP_SOURCE=false
+			;;
+		C)
+			COMPILE=false
+			;;
+		j)
+			CONCURRENCY=$OPTARG
+			;;
+		h)
+			usage
+			exit
+			;;
+		*)
+			return 1
+			;;
+		esac
+	done
+
+	(( OPTIND -= 1 )) || true
+	shift $OPTIND || true
+	DATA_DIR="$1"
+	OUTPUT_DIR="$2"
+
+	if [[ "$DATA_DIR" = "" || "$OUTPUT_DIR" = "" ]]; then
+		usage
+		exit 1
+	fi
+	if [[ ! -e "$DATA_DIR" ]]; then
+		echo "ERROR: $DATA_DIR doesn't exist."
+		exit 1
+	fi
+	if [[ ! -e "$OUTPUT_DIR" ]]; then
+		echo "ERROR: $OUTPUT_DIR doesn't exist."
+		exit 1
+	fi
+}
+
+
+parse_options "$@"
+DATA_DIR=`cd "$DATA_DIR" && pwd`
+OUTPUT_DIR=`cd "$OUTPUT_DIR" && pwd`
+if [[ ! -e "$DATA_DIR/mock" ]]; then
+	echo "ERROR: data directory $DATA_DIR not set up. Please run ./setup first."
+	exit 1
+fi
 
 exec docker run \
 	--rm \
@@ -15,6 +104,14 @@ exec docker run \
 	-v "$SELFDIR/internal:/system:ro" \
 	-v "$DATA_DIR/mock:/var/lib/mock" \
 	-v "$OUTPUT_DIR:/output" \
+	-e "APP_UID=`id -u`" \
+	-e "APP_GID=`id -g`" \
+	-e "X86_BINARIES=$X86_BINARIES" \
+	-e "X64_BINARIES=$X64_BINARIES" \
+	-e "CONCURRENCY=$CONCURRENCY" \
+	-e "SETUP_SOURCE=$SETUP_SOURCE" \
+	-e "COMPILE=$COMPILE" \
+	-e "SANITY_CHECK_OUTPUT=$SANITY_CHECK_OUTPUT" \
 	phusion/ruby-traveler-builder \
 	/system/my_init --quiet --skip-runit --skip-startup-files -- \
 	/system/build
diff --git a/internal/build b/internal/build
--- a/internal/build
+++ b/internal/build
@@ -7,13 +7,48 @@ function do_build()
 	local name="$2"
 	local root=/var/lib/mock/$chroot_name/root
 
+	# Initialize parameters
 	rm -rf $root/system $root/output
 	mkdir $root/system $root/output
 	cp /system/* $root/system/
+	echo $APP_UID > $root/system/APP_UID
+	echo $APP_GID > $root/system/APP_GID
+	echo $CONCURRENCY > $root/system/CONCURRENCY
+	echo $SETUP_SOURCE > $root/system/SETUP_SOURCE
+	echo $COMPILE > $root/system/COMPILE
+	echo $SANITY_CHECK_OUTPUT > $root/system/SANITY_CHECK_OUTPUT
+
+	# Build the binaries
 	/system/setuser app /usr/bin/mock -r $chroot_name --quiet --shell /system/build-inside-mock
+
+	# Move build result to proper output directory
+	rm -rf /output/$name
 	mkdir -p /output/$name
+	chown $APP_UID:$APP_GID /output/$name
 	cp -dpR $root/output/* /output/$name/
+
+	# Cleanup
 	rm -rf $root/system $root/output
 }
 
-do_build epel-5-i386 x86
+if $X86_BINARIES; then
+	echo "------------ Building x86 binaries ------------"
+	(
+		set -x
+		do_build epel-5-i386 x86
+	)
+	if [[ $? != 0 ]]; then
+		exit 1
+	fi
+fi
+if $X64_BINARIES; then
+	echo
+	echo "------------ Building x86_64 binaries ------------"
+	(
+		set -x
+		do_build epel-5-x86_64 x86_64
+	)
+	if [[ $? != 0 ]]; then
+		exit 1
+	fi
+fi
diff --git a/internal/setup b/internal/setup
--- a/internal/setup
+++ b/internal/setup
@@ -44,13 +44,21 @@ echo "---------- Setting up i386 chroot -----------"
 	set -x
 	setup_chroot epel-5-i386
 )
+if [[ $? != 0 ]]; then
+	echo "*** Failed setting up i386 chroot"
+	exit 1
+fi
 
 echo
 echo "---------- Setting up x86_64 chroot -----------"
 (
 	set -x
-	setup_chroot epel-6-i386
+	setup_chroot epel-5-x86_64
 )
+if [[ $? != 0 ]]; then
+	echo "*** Failed setting up x86_64 chroot"
+	exit 1
+fi
 
 if $DOWNLOAD_RUBY; then
 	echo
