OS X build script aborts if ~/.bundle/config exists
Prevents problems like https://github.com/phusion/traveling-ruby/issues/29#issuecomment-70272555

diff --git a/osx/build b/osx/build
--- a/osx/build
+++ b/osx/build
@@ -177,6 +177,12 @@ fi
 if [[ "$GEMFILE" != "" ]]; then
 	GEMFILE="`absolute_path \"$GEMFILE\"`"
 fi
+if [[ -e ~/.bundle/config ]]; then
+	echo "ERROR: ~/.bundle/config detected. Global Bundler configuration" \
+		"could conflict with this build script, so please remove" \
+		"~/.bundle/config first."
+	exit 1
+fi
 
 
 #######################################
