Work in progress

diff --git a/linux/build b/linux/build
--- a/linux/build
+++ b/linux/build
@@ -6,8 +6,7 @@ SELFDIR=`cd "$SELFDIR" && pwd`
 
 RUNTIME_DIR=
 OUTPUT_DIR=
-X86_BINARIES=true
-X64_BINARIES=true
+ARCHITECTURE=
 CONCURRENCY=2
 SETUP_SOURCE=true
 COMPILE=true
@@ -20,10 +19,7 @@ function usage()
 	echo "Build Traveling Ruby binaries."
 	echo
 	echo "Options:"
-	echo "  -t         Only build 32-bit binaries"
-	echo "  -T         Do not build 32-bit binaries"
-	echo "  -s         Only build 64-bit binaries"
-	echo "  -S         Do not build 64-bit binaries"
+	echo "  -a NAME    Architecture to setup (x86, x86_64)"
 	echo
 	echo "  -E         Do not setup source"
 	echo "  -C         Do not compile Ruby"
@@ -37,21 +33,10 @@ function parse_options()
 {
 	local OPTIND=1
 	local opt
-	while getopts "tTsSECGj:h" opt; do
+	while getopts "a:ECGj:h" opt; do
 		case "$opt" in
-		t)
-			X86_BINARIES=true
-			X64_BINARIES=false
-			;;
-		T)
-			X86_BINARIES=false
-			;;
-		s)
-			X86_BINARIES=false
-			X64_BINARIES=true
-			;;
-		S)
-			X64_BINARIES=false
+		a)
+			ARCHITECTURE=$OPTARG
 			;;
 		E)
 			SETUP_SOURCE=false
@@ -92,6 +77,10 @@ function parse_options()
 		echo "ERROR: $OUTPUT_DIR doesn't exist."
 		exit 1
 	fi
+	if [[ "$ARCHITECTURE" = "" ]]; then
+		echo "ERROR: please specify an architecture with -a."
+		exit 1
+	fi
 }
 
 
@@ -112,8 +101,8 @@ exec docker run \
 	-v "$OUTPUT_DIR:/output" \
 	-e "APP_UID=`id -u`" \
 	-e "APP_GID=`id -g`" \
-	-e "X86_BINARIES=$X86_BINARIES" \
-	-e "X64_BINARIES=$X64_BINARIES" \
+	-e "RUBY_VERSION=`cat \"$SELFDIR/../RUBY_VERSION.txt\"`" \
+	-e "ARCHITECTURE=$ARCHITECTURE" \
 	-e "CONCURRENCY=$CONCURRENCY" \
 	-e "SETUP_SOURCE=$SETUP_SOURCE" \
 	-e "COMPILE=$COMPILE" \
diff --git a/linux/setup-runtime b/linux/setup-runtime
--- a/linux/setup-runtime
+++ b/linux/setup-runtime
@@ -5,6 +5,7 @@ SELFDIR=`dirname "$0"`
 SELFDIR=`cd "$SELFDIR" && pwd`
 
 RUNTIME_DIR=
+ARCHITECTURE=
 INITIALIZE=true
 DOWNLOAD_RUBY=true
 
@@ -14,19 +15,23 @@ function usage()
 	echo "Sets up the Traveling Ruby build system's runtime."
 	echo
 	echo "Options:"
-	echo "  -i      Only initialize chroot environment"
-	echo "  -I      Do not initialize chroot environments"
-	echo "  -r      Only download Ruby"
-	echo "  -R      Do not download Ruby"
-	echo "  -h      Show this help"
+	echo "  -a NAME  Architecture to setup (x86, x86_64)"
+	echo "  -i       Only initialize chroot environment"
+	echo "  -I       Do not initialize chroot environment"
+	echo "  -r       Only download Ruby"
+	echo "  -R       Do not download Ruby"
+	echo "  -h       Show this help"
 }
 
 function parse_options()
 {
 	local OPTIND=1
 	local opt
-	while getopts "iIrRh" opt; do
+	while getopts "a:iIrRh" opt; do
 		case "$opt" in
+		a)
+			ARCHITECTURE=$OPTARG
+			;;
 		i)
 			INITIALIZE=true
 			DOWNLOAD_RUBY=false
@@ -63,6 +68,10 @@ function parse_options()
 		echo "ERROR: $RUNTIME_DIR doesn't exist."
 		exit 1
 	fi
+	if [[ "$ARCHITECTURE" = "" ]]; then
+		echo "ERROR: please specify an architecture with -a."
+		exit 1
+	fi
 }
 
 
@@ -76,6 +85,8 @@ exec docker run \
 	-v "$SELFDIR/internal:/system:ro" \
 	-v "$SELFDIR/../shared:/system_shared:ro" \
 	-v "$RUNTIME_DIR/mock:/var/lib/mock" \
+	-e "RUBY_VERSION=`cat \"$SELFDIR/../RUBY_VERSION.txt\"`" \
+	-e "ARCHITECTURE=$ARCHITECTURE" \
 	-e "INITIALIZE=$INITIALIZE" \
 	-e "DOWNLOAD_RUBY=$DOWNLOAD_RUBY" \
 	phusion/ruby-traveler-builder \
