OSX: build supported on x86_64 and arm64 platforms

diff --git a/osx/internal/check_requirements b/osx/internal/check_requirements
--- a/osx/internal/check_requirements
+++ b/osx/internal/check_requirements
@@ -1,14 +1,15 @@
 #!/bin/bash
+
 set -e
 
 XCODEPATH=$(xcode-select -p)
-
-# FIXME: determine the minimal version of SDK to use on ARM64
-if [[ ! -e "$XCODEPATH/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk" ]]; then
-	echo "*** ERROR: the macOS 12.1 SDK is required. Please refer to" \
-		"https://github.com/FooBarWidget/traveling-ruby/blob/main/osx/README.md" \
-		"for installation instructions." >&2
-	exit 1
+if [[ "$XCODEPATH" == "/Library/Developer/CommandLineTools" ]]; then
+  XCODEPATH="$XCODEPATH/SDKs/MacOSX.sdk"
+elif [[ "$XCODEPATH" == "/Applications/Xcode.app/Contents/Developer" ]]; then
+  XCODEPATH="$XCODEPATH/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
+else
+  echo "*** ERROR: unknown developer path \"$XCODEPATH\""
+  exit 1
 fi
 
 if [[ -e /usr/local/include ]]; then
diff --git a/osx/setup-runtime b/osx/setup-runtime
--- a/osx/setup-runtime
+++ b/osx/setup-runtime
@@ -9,7 +9,7 @@ source "$SELFDIR/../shared/library.sh"
 TEMPDIR=
 
 RUNTIME_DIR=
-CONCURRENCY=`sysctl -n hw.ncpu`
+CONCURRENCY=$(sysctl -n hw.ncpu)
 FORCE_CCACHE=false
 SKIP_CCACHE=false
 FORCE_CMAKE=false
@@ -430,12 +430,17 @@ elif [[ ! -e "$RUNTIME_DIR/lib/openssl-ok" ]] || $FORCE_OPENSSL; then
 	echo "Entering $RUNTIME_DIR/openssl-$OPENSSL_VERSION"
 	pushd openssl-$OPENSSL_VERSION >/dev/null
 
-	run ./Configure darwin64-arm64-cc --prefix="$RUNTIME_DIR" --openssldir="$RUNTIME_DIR/openssl" threads zlib shared
-
-	# FIXME: maybe -j more than 1 will work in 2022?
-	# For some reason the -j1 is explicitly required. Otherwise, running `make -j2`
-	# on the Makefile which invoked setup-runtime could somehow pass the -j2 to sub-makes.
-	run make -j1
+	ARCH=$(uname -m)
+	if [[ "$ARCH" == "x86_64" ]]; then
+		BUILDTARGET="darwin64-x86_64-cc"
+	elif [[ "$ARCH" == "arm64" ]]; then
+		BUILDTARGET="darwin64-arm64-cc"
+	else
+		echo "*** ERROR: unknown architecture, don't know how to build"
+		exit 1
+	fi
+	run ./Configure "$BUILDTARGET" --prefix="$RUNTIME_DIR" --openssldir="$RUNTIME_DIR/openssl" threads zlib shared
+	run make -j$CONCURRENCY
 	run make install_sw
 
 	echo "Leaving source directory"
